apiVersion: apps/v1
kind: Deployment
metadata:
  name: scse-mdp-validator
  labels:
    app: mdp-validator
    app.kubernetes.io/name: "mdp-validator"
    app.kubernetes.io/instance: "mdp-validator-prod"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "server"
    app.kubernetes.io/part-of: "mdp-validator"
    app.kubernetes.io/managed-by: "argo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdp-validator
  template:
    metadata:
      labels:
        app: mdp-validator
    spec:
      containers:
        - name: mdp-validator
          image: itachi1706/personal-docker-images:scse-mdp-validator
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 40Mi
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-creds