apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "mdp-validator"
    app.kubernetes.io/instance: "mdp-validator-prod"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: "configuration"
    app.kubernetes.io/part-of: "mdp-validator"
    app.kubernetes.io/managed-by: "argo"
  name: scse-mdp-validator-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: mdp-validator
  type: ClusterIP
  internalTrafficPolicy: Cluster
